//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63132244.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public string Ma_HoaDon { get; set; }
        public string Ma_SP { get; set; }
        public decimal KhoiLuong { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual Sanpham Sanpham { get; set; }
    }
}
