//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63132244.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanTri
    {
        public string TaiKhoan { get; set; }
        public string Password { get; set; }
        public string HoTen { get; set; }
        public string DienThoai { get; set; }
        public string Avatar { get; set; }
        public Nullable<bool> admin { get; set; }
    }
}
